const prefix = 'PlaylistEvents';
export default {
  PLAYLIST_LOADED: `${prefix}.PLAYLIST_LOAD`,
  PLAYLIST_LOAD_ERROR: `${prefix}.PLAYLIST_LOAD_ERROR`,
  SONG_ADDED: `${prefix}.SONG_ADDED`,
  ERROR_ADDING_SONG: `${prefix}.ERROR_ADDING_SONG`,
  ITEM_DELTETED: `${prefix}.ITEM_DELTETED`,
  ERROR_DELETING_PLAYLIST_ITEM: `${prefix}.ERROR_DELETING_PLAYLIST_ITEM`,
  PLAYLIST_CLEARED: `${prefix}.PLAYLIST_CLEARED`,
  ERROR_CLEARING_PLAYLIST: `${prefix}.ERROR_CLEARING_PLAYLIST`,
  ITEM_MOVED: `${prefix}.ITEM_MOVED`,
  ERROR_MOVING_ITEM: `${prefix}.ERROR_MOVING_ITEM`,
  SKIP_ITEM_COMPLETE: `${prefix}.SKIP_ITEM_COMPLETE`,
  SKIP_ITEM_ERROR: `${prefix}.SKIP_ITEM_ERROR`,
  CURRENT_ITEM_LOADED: `${prefix}.CURRENT_ITEM_LOADED`,
  CURRENT_ITEM_LOAD_ERROR: `${prefix}.CURRENT_ITEM_LOAD_ERROR`
};
